In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
#test powiekszania srodka macierzy - tutaj rozmiar macierzy x0.1


#funkcja przyjmuje macierz o rozmiarze 120x120 z LICZBAMI RZECZYWISTYMI, zwraca macierz o tym samym rozmiarze
#złożoną z 60 środkowych wierszy i 60 środkowych kolumn oryginału poprzetykanych wierszami i kolmunami zer
def insert_zeros(M):
    M_cut = M[30:90,30:90]
#    print (M_cut.shape)
#    print(M_cut)
    A = np.zeros((120,120))
    A[::2,::2] = M_cut
    return (A)



#funkcja przyjmuje macierz o rozmiarze 120x120 z LICZBAMI ZŁOŻONYMI, zwraca macierz o tym samym rozmiarze
#złożoną z 60 środkowych wierszy i 60 środkowych kolumn poprzetykanych wierszami i kolmunami zer
def insert_zeros_complex(M):
    M_cut = M[30:90,30:90]
    print (M_cut.shape)
    A = np.zeros((120,120),dtype=complex)
    A[::2,::2] = M_cut
    print (A)

    
def insert_zeros_complex(M):
    M_cut = M[30:90,30:90]
    print (M_cut.shape)
    A = np.zeros((120,120),dtype=complex)
    A[::2,::2] = M_cut
    print (A)

    
    
x_range = np.linspace(-1,-0.3,120)
y_range = np.linspace(0,-0.7,120)

C = np.zeros((120,120),dtype=complex)

for i in range(120):
    for j in range(120):
        C[i][j]=complex(x_range[j],y_range[i])
        
        
        
insert_zeros_complex(C)
        



(60, 60)
[[-0.82352941-0.17647059j  0.        +0.j         -0.81764706-0.17647059j
  ...  0.        +0.j         -0.47647059-0.17647059j
   0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.j
  ...  0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [-0.82352941-0.18235294j  0.        +0.j         -0.81764706-0.18235294j
  ...  0.        +0.j         -0.47647059-0.18235294j
   0.        +0.j        ]
 ...
 [ 0.        +0.j          0.        +0.j          0.        +0.j
  ...  0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [-0.82352941-0.52352941j  0.        +0.j         -0.81764706-0.52352941j
  ...  0.        +0.j         -0.47647059-0.52352941j
   0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.j
  ...  0.        +0.j          0.        +0.j
   0.        +0.j        ]]


In [12]:
#prostszy test - bez złożónych

def insert_zeros(M):
    M_cut = M[30:90,30:90]
#    print (M_cut.shape)
#    print(M_cut)
    A = np.zeros((120,120))
    A[::2,::2] = M_cut
    return (A)



C = np.arange(1,14401)
C = C.reshape((120,120))

        
        
print(C)
insert_zeros(C)

[[    1     2     3 ...   118   119   120]
 [  121   122   123 ...   238   239   240]
 [  241   242   243 ...   358   359   360]
 ...
 [14041 14042 14043 ... 14158 14159 14160]
 [14161 14162 14163 ... 14278 14279 14280]
 [14281 14282 14283 ... 14398 14399 14400]]
(60, 60)
[[ 3631  3632  3633 ...  3688  3689  3690]
 [ 3751  3752  3753 ...  3808  3809  3810]
 [ 3871  3872  3873 ...  3928  3929  3930]
 ...
 [10471 10472 10473 ... 10528 10529 10530]
 [10591 10592 10593 ... 10648 10649 10650]
 [10711 10712 10713 ... 10768 10769 10770]]
[[ 3631.     0.  3632. ...     0.  3690.     0.]
 [    0.     0.     0. ...     0.     0.     0.]
 [ 3751.     0.  3752. ...     0.  3810.     0.]
 ...
 [    0.     0.     0. ...     0.     0.     0.]
 [10711.     0. 10712. ...     0. 10770.     0.]
 [    0.     0.     0. ...     0.     0.     0.]]


In [3]:
#test powiekszania srodka macierzy - tutaj rozmiar macierzy x0.1


#funkcja przyjmuje macierz o rozmiarze 120x120 z LICZBAMI RZECZYWISTYMI, zwraca macierz o tym samym rozmiarze
#złożoną z 60 środkowych wierszy i 60 środkowych kolumn oryginału poprzetykanych wierszami i kolmunami zer
#UWAGA 120-ta kolumna to zera. 120-ty wiersz to zera
def insert_zeros(M):
    M_cut = M[30:90,30:90]
#    print (M_cut.shape)
#    print(M_cut)
    A = np.zeros((120,120))
    A[::2,::2] = M_cut
    return (A)



#funkcja przyjmuje macierz o rozmiarze 120x120 z LICZBAMI ZŁOŻONYMI, zwraca macierz o tym samym rozmiarze
#złożoną z 60 środkowych wierszy i 60 środkowych kolumn poprzetykanych wierszami i kolmunami zer
#UWAGA 60-ta kolumna to zera. 60-ty wiersz to zera
def insert_zeros_complex(M):
    M_cut = M[30:90,30:90]
    print (M_cut.shape)
    A = np.zeros((120,120),dtype=complex)
    A[::2,::2] = M_cut
    print (A)


#UWAGA 60-ta kolumna to zera. 60-ty wiersz to zera - dlatego do wyliczania średnich będzie brana macierz 121x121,
#a potem przycięta do 120x120
def insert_zeros_complex_mean(M):
    M_cut = M[30:91,30:91]
    print (M_cut.shape)
    A = np.zeros((122,122),dtype=complex)
    A[::2,::2] = M_cut
    print (A)
    print(A.shape)
    for i in range(121):
        for j in range(121):
            if (i%2 == 0) and (j%2 != 0):
                A[i][j] = (A[i][j-1]+A[i][j+1])/2
            elif (i%2 != 0) and (j%2 == 0):
                A[i][j] = (A[i-1][j]+A[i+1][j])/2
            elif (i%2 != 0) and (j%2 != 0):
                A[i][j] = (A[i-1][j-1]+A[i-1][j+1]+A[i+1][j-1]+A[i+1][j+1])/4
            else:
                pass
    print(A)
    A = A[:120,:120]
    print(A)
    print(A.shape)

    
    
x_range = np.linspace(-1,-0.3,120)
y_range = np.linspace(0,-0.7,120)

C = np.zeros((120,120),dtype=complex)

for i in range(120):
    for j in range(120):
        C[i][j]=complex(x_range[j],y_range[i])
        
        
        
insert_zeros_complex_mean(C)

(61, 61)
[[-0.82352941-0.17647059j  0.        +0.j         -0.81764706-0.17647059j
  ...  0.        +0.j         -0.47058824-0.17647059j
   0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.j
  ...  0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [-0.82352941-0.18235294j  0.        +0.j         -0.81764706-0.18235294j
  ...  0.        +0.j         -0.47058824-0.18235294j
   0.        +0.j        ]
 ...
 [ 0.        +0.j          0.        +0.j          0.        +0.j
  ...  0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [-0.82352941-0.52941176j  0.        +0.j         -0.81764706-0.52941176j
  ...  0.        +0.j         -0.47058824-0.52941176j
   0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.j
  ...  0.        +0.j          0.        +0.j
   0.        +0.j        ]]
(122, 122)
[[-0.82352941-0.17647059j -0.82058824-0.17647059j -0.81764706-0.17647059j
  ... -0.47352941-